/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    Header: typeof import('./src/components/Header.vue')['default']
    NoteListItem: typeof import('./src/components/notes/NoteListItem.vue')['default']
    NotesList: typeof import('./src/components/notes/NotesList.vue')['default']
    NoteViewer: typeof import('./src/components/notes/NoteViewer.vue')['default']
    RegisterModal: typeof import('./src/components/AuthenticateComponents/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
