/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormRadioGroup: typeof import('bootstrap-vue-next')['BFormRadioGroup']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    EditBodyCompositionMeasurementsModal: typeof import('./src/components/FitnessComponents/EditBodyCompositionMeasurementsModal.vue')['default']
    EditWorkoutsModal: typeof import('./src/components/FitnessComponents/EditWorkoutsModal.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IIcBaselineDelete: typeof import('~icons/ic/baseline-delete')['default']
    IMdiEdit: typeof import('~icons/mdi/edit')['default']
    LineChart: typeof import('./src/components/FitnessComponents/Charts/LineChart.vue')['default']
    NewBodyCompositionMeasurementsModal: typeof import('./src/components/FitnessComponents/NewBodyCompositionMeasurementsModal.vue')['default']
    NewWorkoutModal: typeof import('./src/components/FitnessComponents/NewWorkoutModal.vue')['default']
    NoteListItem: typeof import('./src/components/notes/NoteListItem.vue')['default']
    NotesList: typeof import('./src/components/notes/NotesList.vue')['default']
    NoteViewer: typeof import('./src/components/notes/NoteViewer.vue')['default']
    RegisterModal: typeof import('./src/components/AuthenticateComponents/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
